name: Build

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.12.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - run: echo '##vso[build.updatebuildnumber]$(version.GitVersion_SemVer)'
      displayName: 'Updating build number' 
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"        
    - name: Restore dependencies
      run: dotnet restore ./Source/Scotec.ILMerge.MSBuild.Task.sln
    - name: Build
      run: dotnet build --no-restore ./Source/Scotec.ILMerge.MSBuild.Task.sln -c Release -p:Version=$GITVERSION_ASSEMBLYSEMVER -p:PackageVersion=$GITVERSION_SEMVER -p:CompanyName="scotec Software Solutions AB"
    - name: Pack
      run: dotnet pack --no-restore --no-build ./Source/Scotec.ILMerge.MSBuild.Task.sln -c Release -p:Version=$GITVERSION_ASSEMBLYSEMVER -p:PackageVersion=$GITVERSION_SEMVER -p:CompanyName="scotec Software Solutions AB"
